<?php echo $head; ?>
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />
allah is one.<br />